### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by InstanceOfMichael** [xreader/whois#3]
```
var whois = require('whois-ux');

whois.whois('139.130.4.5', function (err, data){
    console.log(JSON.stringify(data));
});
```

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn whois ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

I get the same result when substituting ``139.130.4.5`` for ``google.com``.

**Comment by xreader** [comment]
What OS are you using?

**Comment by InstanceOfMichael** [comment]
Ubuntu, I think this was solved by ``apt-get install whois``.

**Comment by xreader** [comment]
I updated install section in README
